### ISSUE TITLE
CPU coding style

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/www#3]
Following up from [another issue](https://github.com/ComputationalProteomicsUnit/Pbase/issues/38) where @sgibb suggested

> BTW: Do we need an CPU R style guide? I personally don't like the Hadley's snake_case. In general we use the [Bioc Coding Style](https://www.bioconductor.org/developers/how-to/coding-style/), or?

I generally follow the Bioc style (see the [wiki](https://github.com/ComputationalProteomicsUnit/www/wiki)). I just wanted that *private* function to somewhat stick out, here. I certainly wouldn't name an exported snake_case function. 

Opening up the discussion more widely. @sgibb @lmsimp @jotsetung @TomSmithCGAT  @mchiapello

**Comment by sgibb** [comment]
I always use (and really like :wink:) the dot prefix for internal/*private* functions: `.internalFunction`

**Comment by jotsetung** [comment]
regarding the snake case - sometimes I find snake case variables within functions easier to read. But for parameters I usually prefer camel caps... seems also people from BioC are starting to switch (Martin Morgan at EuroBioC2016 using snake case variable names).

I can however adapt to your favorite style whatever that is.

**Comment by lgatto** [comment]
Regarding Martin's example, it was not a variable but a helper function called `is_scalar_character` checking whether the variable was a scalar of character (of length 1) - see [here](https://github.com/mtmorgan/Elbo/blob/master/R/utilities.R#L6-L9).

I wouldn't mind for a group of related internal helper functions: something like `is_scalar_character`, `is_logical_character`, ... that all return a `logical(1)`. I would **hate** a mix of (exported) snake and camel case for one package.

**Comment by lgatto** [comment]
Here are a few other rules:

* Only use generics and methods when using a function is not possible at all, i.e. the same function name is used for different classes (within the same or different package). 

* Before writing a new generic, check if it doesn't already exists in `BiocGenerics` or `ProtGenerics`.

**Comment by lgatto** [comment]
I have added some of these and a new section about package development to the [wiki](https://github.com/ComputationalProteomicsUnit/www/wiki). 

Closing for now but feel free to re-open to discuss R coding style.
